version: "3"
services:
  sonarqube:
    image: sonarqube:9.9.2-community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://192.168.0.101:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    container_name: sonarqube
    volumes:
      - /run/media/byron/Vm/volumes/sonarqube/data:/opt/sonarqube/data
      - /run/media/byron/Vm/volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - /run/media/byron/Vm/volumes/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"