version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: /run/media/byron/Vm/volumes/postgres
